version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: PatientAccountingSystem
      SPRING_THYMELEAF_CACHE: "false"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/PatientAccountingSystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SERVER_TOMCAT_ACCESSLOG_DIRECTORY: /app/logs
      SERVER_TOMCAT_ACCESSLOG_PATTERN: '%h %l %u %t "%r" %s %b'
      SERVER_TOMCAT_ACCESSLOG_PREFIX: access_log
      SERVER_TOMCAT_ACCESSLOG_SUFFIX: .log
      SERVER_TOMCAT_ACCESSLOG_FILE_DATE_FORMAT: yyyy-MM-dd
    volumes:
      - ./logs:/app/logs  # Монтируем директорию для логов
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: PatientAccountingSystem
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
